### ISSUE TITLE
cURL error (deprecated SSL_VERIFYHOST setting)

### ISSUE THREAD

**Issue by aksl** [Paybyway/rest-php-lib#1]
> Notice: curl_setopt(): CURLOPT_SSL_VERIFYHOST with value 1 is deprecated and will be removed as of libcurl 7.28.1. It is recommended to use value 2 instead in .../vendor/paybyway/paybyway/lib/Paybyway/PaybywayCurl.php on line 19

Fix by changing the value of the mentioned setting from `true` to `2`.

**Comment by kkopone** [comment]
This was fixed in version 4.0.0.
